### ISSUE TITLE
Boilerplate broken when including dev screens

### ISSUE THREAD

**Issue by carlos-peru** [infinitered/ignite#1061]
Hi there,

I'm facing a problem with the latest CLI 2.0.0-rc.1. I cannot run the boilerplate with dev screens. I keep getting the following error on both iOS and Android:

`undefined is not an object (evaluating 'RNDeviceInfo.systemManufacturer')`

It only occurs when including dev screen.

Any suggestions?

**Comment by derekgreenberg** [comment]
Verified. I'm experiencing the same problem. Just tried it after updating to CLI 2.0.0-rc.1

**Comment by atonse** [comment]
I'm getting a similar problem. Brand new boilerplate with dev screens missing "Examples/Components/animatableExample.js."

**Comment by atonse** [comment]
After commenting out the import code that was requesting it, I am now getting the error that @carlos-peru is mentioning.

**Comment by skellock** [comment]
Looks like the dependency is missing from https://github.com/infinitered/ignite-dev-screens/blob/master/plugin.js#L25 for `react-native-device-info`.

Short term fix in your current project.

```sh
npm i --save react-native-device-info
react-native link react-native-device-info
```

Until we get this patched up.

**Comment by derekgreenberg** [comment]
Verified the temporary fix from @skellock works. To test, ignite a new project.  In the series of prompts presented as you ignite your new project, select 'Yes' when prompted ``Would you like Ignite Development Screens?` and answer 'none' when prompted for `What vector icon library will you use?`, `What internationalization library will you use?` and `What animation library will you use?`.  Then follow @skellock's instructions to manually add the dependencies your project needs for react-native-device-info. Issues with the vector icon, internationalization and animation libraries will be fixed ASAP.

**Comment by derekgreenberg** [comment]
Verified that fixes to both [ignite-cli](https://github.com/infinitered/ignite/pull/1067) and[ ignite-dev-screens](https://github.com/infinitered/ignite-dev-screens/pull/5) have solved these errors. 

To test, uninstall ignite-cli and re-install the latest version:

```
npm uninstall -g ignite-cli
npm install -g ignite-cli

ignite --version
2.0.0-rc.2
```
Generate a new app and install dev screens and all libraries when prompted.

**Comment by carlos-peru** [comment]
Thanks a lot for the quick resolution!! Awesome project!!

**Comment by therealgilles** [comment]
When will this issue be fixed in a release?

**Comment by KamranKhankhail** [comment]
@derekgreenberg I have uninstalled `ignite-cli` and re-installed latest version that is currently `2.1.0` but issue is still there. I am unable to add `redux-persist`.

**Comment by jjm340** [comment]
The dev screen content does not appear in the folder it's supposed to when I install a new app, this causes the bundler to fail.

**Comment by andretf** [comment]
Same error in 2.1.1. My package.json has the dependency.
`react-native link react-native-device-info` fixed it.

**Comment by kevinvangelder** [comment]
@andretf Would you mind filing that as an issue on the devscreens repo itself? We may not get around to fixing it as dev screens aren't used in Bowser, but the workaround may be useful to other users that hit the same problem. https://github.com/infinitered/ignite-dev-screens/issues/new

**Comment by andretf** [comment]
Sure

**Comment by andyr6381** [comment]
New here, was having a similar issue using node 10 and devscreen folders not being created in the ignite folder, downgraded to node 7.6.0 and everything installed and worked normally.

**Comment by jamonholmgren** [comment]
That's helpful, thanks @andyr6381 . Go ahead and comment on this issue: https://github.com/infinitered/ignite-dev-screens/pull/14

**Comment by HunWalk** [comment]
The boilerplate works with node v8.12.0 on macOS. Well however by default homebrew wants to install node v10.12.0 and with that version the boilerplate is kinda broken.

**Comment by HunWalk** [comment]
Yeah, a slight problem. After the boilerplate was complete i 've had to run npm install because some dependencies were still missing. Is this necessary?

**Comment by jamonholmgren** [comment]
To be honest, I'm not sure! @HunWalk if you could comment on the other issue (this repo is about the Ignite CLI), that might get more attention.
