### ISSUE TITLE
broken generated app :(

### ISSUE THREAD

**Issue by ahmedNY** [infinitered/ignite#512]
HI, 
I wanted to test ignite, which look promising, following the installation instruction:
```bash
yarn global add react-native-ignite
ignite new MyApplication
cd MyApplication
react-native run-android
```
everything went without errors, MyApplication installed on AVD but it gave an error
```
Requiring unknown module "socket.io-client/socket.io".If you are sure the module is there, try restarting the packager or running "npm install".
unknownModuleError
    require.js:147
loadModuleImplementation
    require.js:88
guardedLoadModule
    require.js:65
_require
    require.js:49
<unknown>
    index.js:130
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:65
_require
    require.js:49
<unknown>
    ReactotronConfig.js:3
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:65
_require
    require.js:49
<unknown>
    index.android.js:3
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:58
_require
    require.js:49
global code
    require-0.js:1
```

output of ignite doctor
```
Computer
  Platform: darwin

Ignite
  Version: 1.12.0
  Path: /Users/ahmed/.nvm/versions/node/v6.0.0/bin/ignite

Node
  Version: v6.0.0
  Path: /Users/ahmed/.nvm/versions/node/v6.0.0/bin/node

NPM
  Version: 3.8.6
  Path: /Users/ahmed/.nvm/versions/node/v6.0.0/bin/npm

Yeoman
  Version: 1.8.5

React Native CLI
  Version: 1.2.0

App
  React Native Version: 0.37.0
```

**Comment by skellock** [comment]
Socket.io just released a new version and it broke backwards compatibility :(.

💩 

Any libraries that weren't strict about their dependency version numbers (such as Reactotron), are broken.

I'm working on a fix now.

**Comment by MarlBurroW** [comment]
Same issue here, thank for the fix @skellock !

**Comment by GantMan** [comment]
I guess this is why we should yarn?

**Comment by skellock** [comment]
Yarn wouldn't help us here.  This is just straight-up broken dependency.

I was linking to the their built library, and they just moved that to a sub-directory.

I'm downgrading socket.io's dependencies from `^` (major) to `~` (patch).

**Comment by skellock** [comment]
Good to go again.  Sorry for the hassles everyone.  That blindsided me too.

**Comment by GantMan** [comment]
w00t

**Comment by mykelaballe** [comment]
was this fixed? im still having the same issue. Or do i need to re-install Ignite?

**Comment by MarlBurroW** [comment]
This issue has been fixed by @skellock one month ago.

**Comment by mykelaballe** [comment]
hmm so that means i need to re-install ignite right? since im still having the socket.io error? im currently using react-native 0.32

**Comment by codecounselor** [comment]
I just tried generating a new project for the first time today and I think I'm running into this same issue.  

![image](https://cloud.githubusercontent.com/assets/12678528/22858543/bcf932aa-f08e-11e6-9e08-e8abb1808609.png)

> ignite doctor
```
Computer
  Platform: darwin

Ignite
  Version: 1.13.0
  Path: /Users/nate/.nvm/versions/node/v6.9.5/bin/ignite

Node
  Version: v6.9.5
  Path: /Users/nate/.nvm/versions/node/v6.9.5/bin/node

NPM
  Version: 2.15.11
  Path: /Users/nate/.nvm/versions/node/v6.9.5/bin/npm

Yeoman
  Version: 1.5.1

React Native CLI
  Version: 2.0.1

App
  React Native Version: 0.30.0
```

I've tried several things including running with NPM 3 and NPM 2.  I've installed socket.io-client at the project and global level as well.

And I've tried several suggestions included here https://github.com/facebook/react-native/issues/4968 

This problem seems pretty specific to this issue though, so I'm hoping someone can shed some light.  @skellock can you link to the commit in which you made the 11/27/16 fix? Thanks!

**Comment by skellock** [comment]
Uh oh.  Whenever I see socket.io errors, I immediately get worried.

It straight-up won't work on NPM 2 now.  That I can tell you for sure.

Can you switch to `npm 3` and try with a freshly ignited project?  I see the version of the one you're using is 0.30.0.

If you still encounter troubles, let's start another Issue and reference this one.

**Comment by codecounselor** [comment]
So I think first try was actually with npm v4.  Once I switched to 3 I started getting a different error, seeminly due to an older version of `react-native` as you pointed out.  That confuses me as well, because I just installed ignite for the first time today, have run and update, and have freshly ignited 4 project.  They all install with older dependencies that what is in `https://github.com/infinitered/ignite/blob/master/ignite-base/package.json`.

After I copied the newer dependency versions I started getting the socket.io error again.  I will try a fresh install on another system to make sure I can reproduce this and then open a new issue as you suggest.

Thanks for the quick response.
