### ISSUE TITLE
Windows 10, ignite generate screen style

### ISSUE THREAD

**Issue by giangqaz** [infinitered/ignite#880]
ignite generate screen NewsScreen
generate style file, but it's content is saga content

**Comment by zbtang** [comment]
I have the same issue on MacbookPro.

**Comment by orozcojair** [comment]
what Beta version are you running? I am currently running beta 3 on a Mac and when I generate a new screen I get an almost proper screen.

There is still a little issue that has been resolved here:
https://github.com/infinitered/ignite-ir-boilerplate-2016/pull/2/commits/1955971ad6e55c41738be8632493cc578abc13b4
 which is going to be pushed tomorrow based with my conversation with Jamon

**Comment by mwarger** [comment]
I'm pretty sure he's talking about this.  I'm working on a PR to fix over at https://github.com/infinitered/ignite-ir-boilerplate-2016

https://github.com/mwarger/ignite-ir-boilerplate-2016/blob/master/commands/screen.js#L24

**Comment by zbtang** [comment]
My ignite version is `2.0.0-beta.3`. But still failed. Is there need to reinitialize my project?

**Comment by skellock** [comment]
Thanks @mwarger .  He has a fix incoming shortly.

@zbtang You'll only need to update `ignite-ir-boilerplate-2016` in your devDependencies in your project to pick up the fix when it arrives.
